export const todoStore = [
  {
    id: 100001,
    date: "2018-05-10",
    color: "#3b82f6",
    heading: "Started learning programming",
    desc: "Began exploring programming fundamentals by understanding how computers execute instructions, how variables store data, and how basic logic works using simple examples and practice problems.",
    logDesc: "started coding",
  },
  {
    id: 100002,
    date: "2019-02-18",
    color: "#22c55e",
    heading: "Basic C programming",
    desc: "Learned syntax, loops, conditions, and functions.",
    logDesc: "c basics",
  },
  {
    id: 100003,
    date: "2020-01-12",
    color: "#f97316",
    heading: "JavaScript introduction",
    desc: "Started JavaScript by learning how it runs in the browser, how scripts interact with HTML, and how events, variables, and functions are used to build interactive web pages.",
    logDesc: "js start",
  },
  {
    id: 100004,
    date: "2020-09-05",
    color: "#a855f7",
    heading: "DOM manipulation practice",
    desc: "Manipulated HTML elements dynamically using JavaScript, practiced query selectors, event listeners, and updated UI based on user actions.",
    logDesc: "dom work",
  },
  {
    id: 100005,
    date: "2021-03-14",
    color: "#ef4444",
    heading: "First todo app",
    desc: "Built a simple todo application with add and delete functionality, understood how application state changes and how user input drives UI updates.",
    logDesc: "todo v1",
  },
  {
    id: 100006,
    date: "2022-02-02",
    color: "#0ea5e9",
    heading: "Git and GitHub usage",
    desc: "Learned version control concepts including commits, branches, merges, and resolving conflicts while maintaining a clean project history.",
    logDesc: "git intro",
  },
  {
    id: 100007,
    date: "2023-08-07",
    color: "#14b8a6",
    heading: "Notes feature development",
    desc: "Implemented a notes feature that allows users to write longer text entries, associate them with dates, and manage content efficiently within the application.",
    logDesc: "notes",
  },
  {
    id: 100008,
    date: "2024-01-15",
    color: "#6366f1",
    heading: "Tailwind UI redesign",
    desc: "Redesigned the application interface using Tailwind CSS, focusing on spacing, typography, color consistency, and responsive behavior across screen sizes.",
    logDesc: "ui redo",
  },
  {
    id: 100009,
    date: "2024-03-01",
    color: "#ec4899",
    heading: "Edit and delete functionality",
    desc: "Added full CRUD support by implementing edit and delete actions, ensuring data updates correctly reflect in the UI and stored state.",
    logDesc: "crud",
  },
  {
    id: 100010,
    date: "2024-04-12",
    color: "#f59e0b",
    heading: "Code refactoring",
    desc: "Refactored existing code to improve readability, reduce duplication, and make the todo store logic easier to maintain and extend.",
    logDesc: "refactor",
  },
  {
    id: 100011,
    date: "2024-05-18",
    color: "#3b82f6",
    heading: "Search and filter feature",
    desc: "Implemented text-based search and filtering so users can quickly find notes by keywords in headings or descriptions.",
    logDesc: "search",
  },
  {
    id: 100012,
    date: "2024-06-10",
    color: "#22c55e",
    heading: "LocalStorage persistence",
    desc: "Integrated browser localStorage to persist user data across sessions, preventing data loss on refresh or browser close.",
    logDesc: "storage",
  },
];
